---
title: "FM_Housing Workspace - Alex"
author: "Alex Voigt & Jake Peters"
date: "6/4/2021"
output: html_document
---

```{r}
library(tidyverse)
library(lme4)
library(caret)
```

```{r}
FM_Housing_Clean <- read_csv("../Data/FM_Housing_Clean.csv", col_types = cols(
  `Lease Term` = col_character(),
  `Water Frontage Length` = col_integer(),
  `Postal Code` = col_factor(),
  `Address #` = col_character(),
  `Occupant Phone 2` = col_character(),
  `Finance` = col_character(),
  `Sheyenne Unpd` = col_character()
))
```

```{r}
n<-5
trainIndex <- createFolds(FM_Housing_Clean$`Log Price`)
```


```{r}
n <- 5
resamples <- vector(length=n)
for(i in 1:n) {
  trainIndex <- createDataPartition(FM_Housing_Clean$`Log Price`, p=0.8, list=FALSE)
  FM_Housing_Train <- FM_Housing_Clean[trainIndex,]
  FM_Housing_Test <- FM_Housing_Clean[-trainIndex,]
  scaling <- preProcess(FM_Housing_Train %>% select(`Log Price`, `Log SqFt`, `Total Bedrooms`, `Total Bathrooms`), method=c("YeoJohnson", "center", "scale"))
  trainScaled <- scaling %>% predict(FM_Housing_Train)
  testScaled <- scaling %>% predict(FM_Housing_Test)
  
  #MODEL GOES BELOW
  trainingModel <- lmer(`Log Price`~
                        `Log SqFt`+
                        `Year Built`+
                        `Building Age`+
                        #`Start Date`+
                        `Seasonally-corrected MRI`+
                        `Unemployment-adjusted Affordability Index`+
                        #`CPI`+
                        `Price Index`+
                        `Total Bedrooms`+
                        `Total Bathrooms`+
                        `Garage Stalls`+
                        `Has Air Conditioning`+
                        `New Construction`+
                        `Style Group`+
                        `Roof Group`+
                        `Water Heater Group`+
                        `Kitchen Island`+
                        `Patio`+
                        `Has Deck`+
                        `Has Fence`+
                        `Sprinkler System`+
                        `Gazebo`+
                        `Dock`+
                        `Pool`+
                        `Pantry`+
                        `Walk-in Closet`+
                        `Private Bath`+
                        `Spa/Hot Tub`+
                        `Foundation Group`+
                        `Book Section Group`+
                        `Exterior`+
                        (1+`Log SqFt`|`Census Tract`), data=trainScaled, REML=FALSE, control=lmerControl(calc.derivs=FALSE))
                      
  testedModel <- predict(trainingModel, newdata=testScaled, allow.new.levels=TRUE)

  resamples[i] <- postResample(testedModel, testScaled$`Log Price`)[2]
  
  print(i)
}
summary(trainingModel)
paste(mean(resamples)-2*sd(resamples), mean(resamples), mean(resamples)+2*sd(resamples))
sd(resamples)

FM_Housing_Test$predicted <- predict(trainingModel, newdata=testScaled, allow.new.levels=TRUE)
ggplot() + geom_point(aes(predict(trainingModel), resid(trainingModel)), alpha=0.1) + geom_hline(yintercept=0, color="blue")
```
