---
title: "TractScraper"
author: "Jake Peters"
date: "6/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(magrittr)
library(stringi)
```

## R Markdown
```{r}
FM_Housing_Raw <- read_csv(unz("FM_Housing_Raw.zip", "FM_Housing_Raw.csv"), col_types = cols(
  `Lease Term` = col_character(),
  `Directions` = col_character(),
  `Water Frontage Length` = col_integer()
))
```


```{r}

  latlonhead <- FM_Housing_Raw %>% select(`Geo Lon`, `Geo Lat`) %>% na.omit(latlonhead)
  #latlonhead <- latlonhead %>% tail(50000)
  
  tractvec <- vector(length = nrow(latlonhead))
 for(i in 35001:nrow(latlonhead)) {
  lon <- toString(latlonhead[i,1])
  lat <- toString(latlonhead[i,2])
  
  latlon <- read_html(paste0("https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=",lon,"&y=",lat,"&benchmark=4&vintage=4"))
  
 tractvec[i] <- html_node(latlon,"#pl_gov_census_geo_geocoder_domain_GeographyResult") %>% html_children() %>% extract(5) %>% html_text() %>% 
   str_extract("(?<=TRACT\\: )\\d+")
 if(i %% 1000==0){
   write.csv(as.data.frame(tractvec), paste0("tractvec", toString(i), ".csv"))
   cat(i, "\n")
 }
 }
  
```