---
title: "TractScraper"
author: "Jake Peters"
date: "6/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(magrittr)
library(stringi)
```

## R Markdown
```{r}
FM_Housing_Raw <- read_csv(unz("../Data/FM_Housing_Raw.zip", "FM_Housing_Raw.csv"), col_types = cols(
  `Lease Term` = col_character(),
  `Directions` = col_character(),
  `Water Frontage Length` = col_integer()
))
```

```{r}
FM_Housing_Clean <- FM_Housing_Raw %>% select(-c("Property Type", "Card Format")) #All properties are Residential for both Property Type and Card Format variables
FM_Housing_Clean <- FM_Housing_Clean %>% select(-c("List Number", "Directions")) #Arbitrary values not useful for data mining
FM_Housing_Clean$`Year Built`[FM_Housing_Clean$`Year Built` < 1600 | FM_Housing_Clean$`Year Built` > 2021] <- NA
FM_Housing_Clean <- FM_Housing_Clean %>% mutate("List Price Change":=`List Price`-`Original List Price`)
FM_Housing_Clean <- FM_Housing_Clean %>% mutate("Sold/List Price Difference":=`Sold Price` - `List Price`)
FM_Housing_Clean <- FM_Housing_Clean %>% mutate("Sold/Original List Price Difference":=`Sold Price` - `Original List Price`)

```


```{r}
get_tract <-  function(x,y) {
 return(tract)
}

  latlonframe <- FM_Housing_Clean %>% select(`Geo Lon`, `Geo Lat`)
  latlonhead <- latlonframe %>% head(100)
  tractvec <- vector(length = nrow(latlonhead))
 for(i in 1:nrow(latlonhead)) {
    row <- latlonhead[i,]
    # do stuff with row
  lon <- toString(latlonhead[i,1])
  lat <- toString(latlonhead[i,2])
  latlon <- read_html(paste0("https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x=",lon,"&y=",lat,"&benchmark=4&vintage=4"))
  
 tractvec[i] <- html_node(latlon,"#pl_gov_census_geo_geocoder_domain_GeographyResult") %>% html_children() %>% extract(5) %>% html_text() %>% str_extract("(?<=TRACT\\: )\\d+")
 }
  View(tractvec)
```

