---
title: "FM_Housing"
author: "Alex Voigt & Jake Peters"
date: "6/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
FM_Housing_Raw <- read_csv(unz("../Data/FM_Housing_Raw.zip", "FM_Housing_Raw.csv"), col_types = cols(
  `Lease Term` = col_character(),
  `Directions` = col_character(),
  `Water Frontage Length` = col_integer()
))
```

```{r}
FM_Housing_Clean <- FM_Housing_Raw %>% select(-c("Property Type", "Card Format")) #All properties are Residential for both Property Type and Card Format variables
FM_Housing_Clean <- FM_Housing_Clean %>% select(-c("List Number")) #Arbitrary values not useful for data mining
FM_Housing_Clean <- FM_Housing_Clean %>% mutate("Water Frontage Length" = parse_number("Water Frontage Length", na=character()))
```

```{r}
ggplot(data=FM_Housing_Clean) + geom_histogram(mapping=aes(x=`Original List Price`), bins=250)
ggplot(data=FM_Housing_Clean) + geom_histogram(mapping=aes(x=`List Price`), bins=250)
ggplot(data=FM_Housing_Clean) + geom_histogram(mapping=aes(x=`Sold Price`), bins=250)

median(na.omit(FM_Housing_Clean$`Sold Price`))
median(FM_Housing_Clean$`List Price`)
median(FM_Housing_Clean$`Sold Price`)

ggplot(data=FM_Housing_Clean) + geom_bar(mapping=aes(x=`Style`))
```
```{r}
getHousesOnMarket <- function(currentDate) {
  return(nrow(FM_Housing_Clean %>% filter(`Start Date` <= currentDate & `Pended Date` >= currentDate)))
}

Houses_On_Market <- data.frame("Date"=seq(as.Date("2001-05-01"), as.Date("2021-03-01"), by="days"))
Houses_On_Market <- Houses_On_Market %>% rowwise() %>% mutate("Houses on Market" = getHousesOnMarket(Date))
FM_Housing_Clean <- left_join(FM_Housing_Clean, Houses_On_Market, by=c("Start Date" = "Date")) %>% rename("Houses on Market at Start" = "Houses on Market")
FM_Housing_Clean <- left_join(FM_Housing_Clean, Houses_On_Market, by=c("Pended Date" = "Date")) %>% rename("Houses on Market at Pended" = "Houses on Market")

getHousesOnLocalMarket <- function(currentDate, currentLon, currentLat, milesRadius) {
  return(nrow(FM_Housing_Clean %>% filter(
    `Start Date` <= currentDate &
    `Pended Date` >= currentDate &
    `Geo Lon` >= currentLon-.0185*milesRadius &
    `Geo Lon` <= currentLon+.0185*milesRadius &
    `Geo Lat` >= `Geo Lat`-.0145*milesRadius &
    `Geo Lat` <= currentLat+.0145*milesRadius)))
}

FM_Housing_Clean <- FM_Housing_Clean %>% rowwise() %>% mutate("Houses on Local Market at Start" = getHousesOnLocalMarket(`Start Date`, `Geo Lon`, `Geo Lat`, 1))

# 2:42 to run
```

```{r}
getHousesOnMarket <- function(rowNumber, milesRadius, usePended) {
  if (usePended) {
    thisDate <- FM_Housing_Clean[rowNumber,]$`Pended Date`
  } else {
    thisDate <- FM_Housing_Clean[rowNumber,]$`Start Date`
  }
  
  Global_Market <- FM_Housing_Clean %>% filter(
    `Start Date` <= thisDate &
    `Pended Date` >= thisDate
  )
  
  thisLon <- FM_Housing_Clean[rowNumber,]$`Geo Lon`
  thisLat <- FM_Housing_Clean[rowNumber,]$`Geo Lat`
  
  Local_Market <- Global_Market %>% filter(
    `Geo Lon` >= thisLon-.0185*milesRadius &
    `Geo Lon` <= thisLon+.0185*milesRadius &
    `Geo Lat` >= thisLat-.0145*milesRadius &
    `Geo Lat` <= thisLat+.0145*milesRadius
  )
  return(c(nrow(Global_Market),nrow(Local_Market)))
}

Markets_List <- as.data.frame(matrix(data=NA, nrow=nrow(FM_Housing_Clean), ncol=2))
for(n in 1:nrow(FM_Housing_Clean)) {
  Markets_List[n,] <- getHousesOnMarket(n, 1, FALSE)
}
FM_Housing_Clean <- FM_Housing_Clean %>% cbind(Markets_List)
FM_Housing_Clean <- FM_Housing_Clean %>% rename("Houses on Global Market at Start" = `V1`, "Houses on Local Market at Start" = `V2`)

# 2:46 to run
```