---
title: "FM_Housing Workspace - Alex"
author: "Alex Voigt & Jake Peters"
date: "6/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(lubridate)
```


```{r}
FM_Housing_Raw <- read_csv(unz("../Data/FM_Housing_Raw.zip", "FM_Housing_Raw.csv"), col_types = cols(
  `Lease Term` = col_character(),
  `Directions` = col_character(),
  `Water Frontage Length` = col_integer()
))

FM_Labor_Raw <- read_excel("../Data/FM_Labor_Raw.xlsx")

FM_Income_Raw <- read_excel("../Data/FM_Income_Raw.xlsx")
```

```{r}
FM_Housing_Clean <- FM_Housing_Raw %>% select(-c("Property Type", "Card Format")) #All properties are Residential for both Property Type and Card Format variables
FM_Housing_Clean <- FM_Housing_Clean %>% select(-c("List Number", "Directions")) #Arbitrary values not useful for data mining
FM_Housing_Clean$`Year Built`[FM_Housing_Clean$`Year Built` < 1600 | FM_Housing_Clean$`Year Built` > 2021] <- NA
FM_Housing_Clean <- FM_Housing_Clean %>% mutate("List Price Change":=`List Price`-`Original List Price`)
FM_Housing_Clean <- FM_Housing_Clean %>% mutate("Sold/List Price Difference":=`Sold Price` - `List Price`)
FM_Housing_Clean <- FM_Housing_Clean %>% mutate("Sold/Original List Price Difference":=`Sold Price` - `Original List Price`)

FM_Housing_Clean <- FM_Housing_Clean %>% mutate("Sold Period" = floor_date(`Sold Date`, "month"))

FM_Housing_Clean <- FM_Housing_Clean %>% mutate("Sale to List Ratio" = `Sold Price` / `List Price`)
```

```{r}
FM_Agg_Monthly <- FM_Labor_Raw %>% mutate(Period=as.Date(paste(Year, Period, "01", sep="-"), "%Y-%b-%d"))

FM_Income_Clean <- FM_Income_Raw %>% select(c(Date, Fargo)) %>% rename("Year"=Date) %>% rename("Median Household Income"=Fargo)

FM_Agg_Monthly <- left_join(FM_Agg_Monthly, FM_Income_Clean)

FM_Agg_Monthly <- FM_Agg_Monthly %>% select (-Year) %>% mutate_at(vars(-Period, -CPI, -`Median Household Income`), parse_number)
```

```{r}
getHousesOnMarket <- function(currentDate) {
  return(nrow(FM_Housing_Clean %>% filter(`Start Date` <= currentDate, currentDate <= `Pended Date`)))
}

function(currentDate) {
  FM_Housing_Clean %>% 
}

getHousesSoldMonthly <- function(currentDate) {
  return(nrow(FM_Housing_Clean %>% filter(currentDate - months(1) <= `Pended Date`, `Pended Date` <= currentDate)))
}

getHousesSoldYearly <- function(currentDate) {
  return(nrow(FM_Housing_Clean %>% filter(currentDate - years(1) <= `Pended Date`, `Pended Date` <= currentDate)))
}

getMedianMarketPriceMonthly <- function(currentDate) {
  return(FM_Housing_Clean %>% filter(`Start Date` <= currentDate, currentDate - months(1) <= `Pended Date`) %>% pull(`List Price`) %>% median())
}

getMedianSoldPriceMonthly <- function(currentDate) {
  return(FM_Housing_Clean %>% filter(currentDate - months(1) <= `Pended Date`, `Pended Date` <= currentDate) %>% pull(`Sold Price`) %>% median())
}

getMedianSaleToListMonthly <- function(currentDate) {
  return(FM_Housing_Clean %>% filter(currentDate - months(1) <= `Pended Date`, `Pended Date` <= currentDate) %>% pull(`Sale to List Ratio`) %>% mean())
}

FM_Agg_Monthly <- FM_Agg_Monthly %>% rowwise %>% mutate("Houses on Market" = getHousesOnMarket(Period))
FM_Agg_Monthly <- FM_Agg_Monthly %>% rowwise %>% mutate("Houses Sold in Period" = getHousesSoldMonthly(Period))
FM_Agg_Monthly <- FM_Agg_Monthly %>% rowwise %>% mutate("Sales Rate over past Year" = getHousesSoldYearly(Period)/12)
FM_Agg_Monthly <- FM_Agg_Monthly %>% mutate("Months Remaining Inventory" = `Houses on Market` / `Houses Sold in Period`)
FM_Agg_Monthly <- FM_Agg_Monthly %>% mutate("Seasonally-corrected MRI" = `Houses on Market` / `Sales Rate over past Year`)
FM_Agg_Monthly <- FM_Agg_Monthly %>% rowwise %>% mutate("Median Market Price in Period" = getMedianMarketPriceMonthly(Period))
FM_Agg_Monthly <- FM_Agg_Monthly %>% rowwise %>% mutate("Median Sold Price in Period" = getMedianSoldPriceMonthly(Period))
FM_Agg_Monthly <- FM_Agg_Monthly %>% mutate("Real Median Sold Price in Period" = 261.56*`Median Sold Price in Period` / `CPI`)
FM_Agg_Monthly <- FM_Agg_Monthly %>% mutate("Real Median Market Price in Period" = 261.56*`Median Market Price in Period` / `CPI`)
FM_Agg_Monthly <- FM_Agg_Monthly %>% mutate("Median Sale to List Ratio in Period" = getMedianSaleToListMonthly(Period))
```

```{r}
FM_Agg_Monthly %>% filter(Period >= as.Date("2002-05-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Houses on Market`), color="red") + geom_line(mapping=aes(x=Period, y=`Houses Sold in Period`), colour="blue")

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-05-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Houses on Market`), color="red") + geom_line(mapping=aes(x=Period, y=`Sales Rate over past Year`), colour="blue")

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-05-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Months Remaining Inventory`))

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-05-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Seasonally-corrected MRI`))

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-05-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Median Sold Price in Period`))

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-05-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Real Median Sold Price in Period`))

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-01-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=scale(`Seasonally-corrected MRI`, TRUE, TRUE)), color="red") + geom_line(mapping=aes(x=Period, y=scale(`Real Median Sold Price in Period`, TRUE, TRUE)), colour="blue") + geom_hline(yintercept=0)

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-01-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=scale(`Seasonally-corrected MRI`, TRUE, TRUE)), color="red") + geom_line(mapping=aes(x=Period, y=scale(`Real Median Market Price in Period`, TRUE, TRUE)), colour="blue") + geom_hline(yintercept=0)

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-01-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Real Median Market Price in Period`), color="red") + geom_line(mapping=aes(x=Period, y=`Real Median Sold Price in Period`), colour="blue")

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-01-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Real Median Sold Price in Period`-`Real Median Market Price in Period`))

FM_Agg_Monthly %>% filter(Period >= as.Date("2002-05-01") & Period <= as.Date("2020-01-01")) %>% ggplot() + geom_line(mapping=aes(x=Period, y=`Median Sale to List Ratio in Period`)) + scale_y_log10()
```

```{r}
ggplot(data=FM_Housing_Clean %>% filter(`Geo Lon` >= -96.95, `Geo Lon` <= -96.7, `Geo Lat` >= 46.75, `Geo Lat` <= 47)) + geom_point(mapping=aes(x=`Geo Lon`, y=`Geo Lat`, color=`Map Area`), size=0.75)

ggplot(data=FM_Housing_Clean %>% filter(`Geo Lon` >= -96.95, `Geo Lon` <= -96.7, `Geo Lat` >= 46.75, `Geo Lat` <= 47, `Sold Price` >= 10000)) + geom_point(mapping=aes(x=`Geo Lon`, y=`Geo Lat`, color=log(`Sold Price`, base=1.1)), size=0.75) + scale_color_continuous(low="yellow", high="red") + facet_wrap(~`Map Area`)

```



