---
title: "Stories"
author: "Alex Voigt"
date: "7/8/2021"
output: html_document
---

```{r}
#INITIALIZATION
#Run before other chunks

##Loads in necessary libraries
library(tidyverse)
library(scales)
library(lubridate)

#Loads datasets
FM_Housing_Clean <- read_csv("../Data/FM_Housing_Clean.csv.gz", col_types = cols(
  `Lease Term` = col_character(),
  `Water Frontage Length` = col_integer(),
  `Postal Code` = col_character(),
  `Address #` = col_character(),
  `Occupant Phone 2` = col_character(),
  `Finance` = col_character(),
  `Sheyenne Unpd` = col_character(),
  `Garage Type` = col_character()
))
FM_Agg_Monthly <- read_csv("../Data/FM_Agg_Monthly.csv")

#Preprocessing for data
FM_Housing_Clean$`Sales Period` = floor_date(FM_Housing_Clean$`Sold Date`, "month")
```

```{r}
###THE MARKET OVER TIME: What drives price changes?

#Here is a plot of median sales price of homes sold from 2000-2020 in the Fargo-Moorhead area (about 60,000 sales records in total), adjusted for inflation and displayed in December 2020 dollars.
FM_Housing_Clean %>%
  filter(`New Construction`=="Yes") %>%
  group_by(`Sales Period`) %>%
  arrange(desc(`Sales Period`)) %>%
  summarize("Median Price"=median(`Real Sold Price`)) %>%
  fill(`Median Price`) %>%
  ggplot() +
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_line(aes(x=`Sales Period`, y=`Median Price`), color="blue") +
  xlim(as.Date("2000-01-01"), as.Date("2021-01-01")) +
  theme_bw() +
  ylim(150000,350000)
#As we can see, the house of prices increases relative even to dollar inflation. Why is this?

#The first clue may be to look at the actual affordability of homes, rather than the sticker price. That value is not paid up front, rather it usually takes the form of a mortgage over at least 20 years. A more helpful metric, then, may be to look at "affordability" -- that is, comparing yearly household income to yearly payments on a home. Here we've plotted an "affordability index" that looks at the ratio of the median household income to the income necessary to secure a mortgage on the median-priced home (4 times the yearly payment on said home).
FM_Agg_Monthly %>%
  ggplot() +
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_line(aes(x=`Period`, y=`Affordability Index`/100), color="blue") +
  xlim(as.Date("2000-01-01"), as.Date("2021-01-01")) +
  theme_bw()
#It looks like affordability does not have the same clear upward trend as sales price.

#Plot of seasonally-corrected 'months remaining inventory', which is a measure of supply to demand. It looks at the number of houses on the market at any given time and compares it to the sales rate at the same time, to determine how much stock is available for buyers. Essentially, it says how many months it would take to sell all the houses currently on the market, assuming no new houses are put on the market and the sales rate remains constant
FM_Agg_Monthly %>%
  ggplot() + 
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_line(aes(x=`Period`, y=`Seasonally-corrected MRI`), color="blue") +
  xlim(as.Date("2000-01-01"), as.Date("2021-01-01")) +
  theme_bw()

#Plo
FM_Housing_Clean %>%
  group_by(`Sales Period`) %>%
  arrange(desc(`Sales Period`)) %>%
  summarize("Median Sales Price"=median(`Sold Price`)) %>%
  left_join(FM_Agg_Monthly %>% select(c("Period", "Median Income")), by=c("Sales Period"="Period")) %>%
  ggplot() +
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_line(aes(x=`Sales Period`, y=`Median Sales Price`), color="blue") +
  geom_line(aes(x=`Sales Period`, y=`Median Income`), color="red") +
  xlim(as.Date("2000-01-01"), as.Date("2021-01-01")) +
  ylim(0,300000) +
  theme_bw()

Poorest_in_2000 <- FM_Housing_Clean %>% filter(`Sales in Tract` > 100) %>%
  group_by(`Census Tract`, "Sales Year"=floor_date(`Sales Period`, "year")) %>%
  summarize("Median Price"=median(`Sold Price`), .groups="keep") %>%
  arrange(`Sales Year`, `Median Price`) %>%
  head(5)

Richest_in_2000 <- FM_Housing_Clean %>% filter(`Sales in Tract` > 100) %>%
  group_by(`Census Tract`, "Sales Year"=floor_date(`Sales Period`, "year")) %>%
  summarize("Median Price"=median(`Sold Price`), .groups="keep") %>%
  arrange(`Sales Year`, desc(`Median Price`)) %>%
  head(5)

#3 of the 5 poorest neighborhoods in 2000 are still the poorest in 2021:
Poorest_in_2021 <- FM_Housing_Clean %>%
  filter(`Sales in Tract` > 100) %>%
  group_by(`Census Tract`, "Sales Year"=floor_date(`Sales Period`, "year")) %>%
  summarize("Median Price"=median(`Sold Price`), .groups="keep") %>%
  arrange(desc(`Sales Year`), `Median Price`) %>%
  head(5)

#4 of the 5 richest neighborhoods in 2000 are still the richest neighborhoods in 2021:
Richest_in_2021 <- FM_Housing_Clean %>%
  filter(`Sales in Tract` > 100) %>%
  group_by(`Census Tract`, "Sales Year"=floor_date(`Sales Period`, "year")) %>%
  summarize("Median Price"=median(`Sold Price`), .groups="keep") %>%
  arrange(desc(`Sales Year`), desc(`Median Price`)) %>%
  head(5)

FM_Housing_Clean %>%
  filter(`Census Tract` %in% Poorest_in_2000$`Census Tract`) %>%
  group_by(`Census Tract`, "Sales Year"=floor_date(`Sales Period`, "year")) %>%
  summarize("Median Price"=median(`Sold Price`), .groups="keep") %>%
  left_join(FM_Agg_Monthly %>% select(c(`Median Sold Price in Period`, `Period`)), by=c("Sales Year"="Period")) %>%
  ggplot() +
  geom_line(mapping=aes(x=`Sales Year`, y=`Median Price`, color=as.character(`Census Tract`))) +
  geom_line(mapping=aes(x=`Sales Year`, y=`Median Sold Price in Period`), color="black", size=1) +
  theme_bw()

FM_Housing_Clean %>%
  filter(`Census Tract` %in% Richest_in_2000$`Census Tract`) %>%
  group_by(`Census Tract`, "Sales Year"=floor_date(`Sales Period`, "year")) %>%
  summarize("Median Price"=median(`Sold Price`), .groups="keep") %>%
  left_join(FM_Agg_Monthly %>% select(c(`Median Sold Price in Period`, `Period`)), by=c("Sales Year"="Period")) %>%
  ggplot() +
  geom_line(mapping=aes(x=`Sales Year`, y=`Median Price`, color=as.character(`Census Tract`))) +
  geom_line(mapping=aes(x=`Sales Year`, y=`Median Sold Price in Period`), color="black", size=1) +
  theme_bw()

##NOTE: North Dakota oil boom started to decline around 2015, causing many people who worked in the oil fields in Williston to move to Fargo. This may be responsible for the sharp incline in square footage noted around 2015-2016, as a wealthier demographic began building new properties in South & West Fargo.
FM_Housing_Clean %>%
  filter(`New Construction`=="Yes") %>%
  group_by(`Sales Period`) %>%
  arrange(desc(`Sales Period`)) %>%
  summarize("Median Square Footage"=median(`Total SqFt.`)) %>%
  fill(`Median Square Footage`) %>%
  ggplot() +
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_line(aes(x=`Sales Period`, y=`Median Square Footage`), color="blue") +
  xlim(as.Date("2000-01-01"), as.Date("2021-01-01")) +
  theme_bw()

FM_Housing_Clean %>%
  filter(`New Construction`=="Yes" & `Sales Period`<as.Date("2021-06-01")) %>%
  group_by(`Sales Period`) %>%
  summarize("New Properties"=n()) %>%
  ggplot(mapping=aes(x=`Sales Period`, y=`New Properties`)) +
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_line(color="grey") +
  geom_smooth(color="black", se=FALSE, span=0.2) +
  theme_bw()

FM_Housing_Clean %>%
  filter(`New Construction`=="Yes" & `Sales Period`< as.Date("2021-06-01") & `Sold Price`<`Median Sold Price in Period`) %>%
  group_by(`Sales Period`) %>%
  summarize("New Properties Below Median Price"=n()) %>%
  ggplot(mapping=aes(x=`Sales Period`, y=`New Properties Below Median Price`)) +
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_line(color="grey") +
  geom_smooth(color="black", se=FALSE, span=0.2) +
  theme_bw()

FM_Housing_Clean %>%
  filter(`New Construction`=="Yes" & `Sales Period`< as.Date("2021-06-01")) %>%
  group_by(`Sales Period`) %>%
  summarize("New Properties"=n()) %>%
  left_join(FM_Housing_Clean %>% filter(`New Construction`=="Yes" & `Sales Period` < as.Date("2021-06-01") & `Sold Price` < `Median Sold Price in Period`) %>% 
  group_by(`Sales Period`) %>%
  summarize("New Properties Below Median Price"=n())) %>%
  ggplot(mapping=aes(x=`Sales Period`, y=`New Properties Below Median Price`/`New Properties`)) +
  geom_line(color="grey") +
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_smooth(color="black", se=FALSE, span=0.2) +
  theme_bw()

FM_Housing_Clean %>%
  group_by(`Sales Period`) %>%
  arrange(desc(`Sales Period`)) %>%
  summarize("Sale to List Ratio"=mean(`Sold Price`/`List Price`)) %>%
  ggplot(aes(x=`Sales Period`, y=`Sale to List Ratio`)) +
  geom_rect(aes(xmin=as.Date("2001-03-01"), xmax=as.Date("2001-11-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2007-12-01"), xmax=as.Date("2009-06-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_rect(aes(xmin=as.Date("2020-02-01"), xmax=as.Date("2020-04-01"), ymin=-Inf, ymax=Inf), alpha=0.01, fill="grey") +
  geom_line(color="grey") +
  geom_smooth(color="black", se=FALSE, span=0.15) +
  geom_hline(yintercept=1, color="black") +
  xlim(as.Date("2000-01-01"), as.Date("2021-01-01")) +
  theme_bw()
```

```{r}
##R CLEANING TUTORIAL
library(tidyverse)                    #Loads an external library of R functions useful for data cleaning

FM_Housing_Clean %>%                  #"FM_Housing_Clean" is the name assigned to our dataset.
                                      #"%>%" indicates sequential events, such that the next line is performed on the output from this line.
  
  group_by(`Garage Type`) %>%         #"Groups" the data by garage type.
                                      #On its own this doesn't change anything, but it allows us to call functions that aggregate data by this group.

  summarize("Number of Entries"=n())  #Outputs each entry for garage type as well as the number of times that entry appears in the dataset.
```

```{r}
FM_Housing_Clean <- FM_Housing_Clean %>%  #"<-" operator is used to assign a variable.
                                          #Here we are replacing the old FM_Housing_Clean with a modified version containing the desired changes.
  
  mutate("Garage Type"=                   #Modifies the "Garage Type" column according to the function passed to it -- here, recode().
    
    recode(`Garage Type`,                 #Looks at the values of "Garage Type" and changes them according to our assignments.
      "A" = "A",                          #Values on the left are transformed into the values on the right.
      "D" = "D",
      "DET" = "D",
      "No" = "D",
      "None" = "None",
      "Select" = "None",
      "Yes" = "A"
    )
  ) %>%
  replace_na(list("Garage Type"="None"))  #Replaces NA values in Garage Type with "None".

FM_Housing_Clean %>%                      #Now we can simply call the same function as before to verify our results.
  group_by(`Garage Type`) %>%    
  summarize("Number of Entries"=n())
```